### ISSUE TITLE
reCAPTCHA not displaying

### ISSUE THREAD

**Issue by shenerd140** [labstack/labstack-node#1]
Please do check the sign-up page because the reCAPTCHA is not displaying in the signup form to validate the user. I tested this in the latest chrome and firefox browser even when javascript is enabled but the reCAPTCHA is not showing.

**Comment by vishr** [comment]
@devswon Are you talking about the main website signup?

**Comment by shenerd140** [comment]
@vishr Yes but after many tries, I finally signed up. When you open the console in the browser and hit the sign up button after filling in the form, an error does show up. It seems there is a problem with the vue-recaptcha library you are using. You should check it up
